[package]
name = "vulkano"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ahash = "0.8.6"
smallvec = "1.11.2"
vulkano = "0.34.1"
winit = { version = "0.30.3", features = ["rwh_05"] }